export const patternsDueDate = [
  "EEEE d MMMM yyyy K:mm a",
  "EEEE d MMMM yyyy h:mm a",
  "EEEE d MMMM yyyy K a",
  "EEEE d MMMM yyyy h a",
  "EEEE d MMMM yyyy H:mm",
  "EEEE d MMMM yyyy k:mm",
  "EEEE d MMMM yyyy",
  "EEEE d MMMM K:mm a",
  "EEEE d MMMM h:mm a",
  "EEEE d MMMM K a",
  "EEEE d MMMM h a",
  "EEEE d MMMM H:mm",
  "EEEE d MMMM k:mm",
  "EEEE d MMMM",
  "EEEE d MMM yyyy K:mm a",
  "EEEE d MMM yyyy h:mm a",
  "EEEE d MMM yyyy K a",
  "EEEE d MMM yyyy h a",
  "EEEE d MMM yyyy H:mm",
  "EEEE d MMM yyyy k:mm",
  "EEEE d MMM yyyy",
  "EEEE d MMM K:mm a",
  "EEEE d MMM h:mm a",
  "EEEE d MMM K a",
  "EEEE d MMM h a",
  "EEEE d MMM H:mm",
  "EEEE d MMM k:mm",
  "EEEE d MMM",
  "EEEE K:mm a",
  "EEEE h:mm a",
  "EEEE K a",
  "EEEE h a",
  "EEEE H:mm",
  "EEEE k:mm",
  "EEEE",
  "EEE d MMMM yyyy K:mm a",
  "EEE d MMMM yyyy h:mm a",
  "EEE d MMMM yyyy K a",
  "EEE d MMMM yyyy h a",
  "EEE d MMMM yyyy H:mm",
  "EEE d MMMM yyyy k:mm",
  "EEE d MMMM yyyy",
  "EEE d MMMM K:mm a",
  "EEE d MMMM h:mm a",
  "EEE d MMMM K a",
  "EEE d MMMM h a",
  "EEE d MMMM H:mm",
  "EEE d MMMM k:mm",
  "EEE d MMMM",
  "EEE d MMM yyyy K:mm a",
  "EEE d MMM yyyy h:mm a",
  "EEE d MMM yyyy K a",
  "EEE d MMM yyyy h a",
  "EEE d MMM yyyy H:mm",
  "EEE d MMM yyyy k:mm",
  "EEE d MMM yyyy",
  "EEE d MMM K:mm a",
  "EEE d MMM h:mm a",
  "EEE d MMM K a",
  "EEE d MMM h a",
  "EEE d MMM H:mm",
  "EEE d MMM k:mm",
  "EEE d MMM",
  "EEE K:mm a",
  "EEE h:mm a",
  "EEE K a",
  "EEE h a",
  "EEE H:mm",
  "EEE k:mm",
  "EEE",
  "d MMMM yyyy K:mm a",
  "d MMMM yyyy h:mm a",
  "d MMMM yyyy K a",
  "d MMMM yyyy h a",
  "d MMMM yyyy H:mm",
  "d MMMM yyyy k:mm",
  "d MMMM yyyy",
  "d MMMM K:mm a",
  "d MMMM h:mm a",
  "d MMMM K a",
  "d MMMM h a",
  "d MMMM H:mm",
  "d MMMM k:mm",
  "d MMMM",
  "d MMM yyyy K:mm a",
  "d MMM yyyy h:mm a",
  "d MMM yyyy K a",
  "d MMM yyyy h a",
  "d MMM yyyy H:mm",
  "d MMM yyyy k:mm",
  "d MMM yyyy",
  "d MMM K:mm a",
  "d MMM h:mm a",
  "d MMM K a",
  "d MMM h a",
  "d MMM H:mm",
  "d MMM k:mm",
  "d MMM",
];


export const patternsTime = ["K:mm a", "h:mm a", "K a", "h a", "H:mm", "k:mm"];